# Generated by Django 3.2.9 on 2022-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kobo_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='締切日')),
                ('prize', models.TextField(blank=True, null=True, verbose_name='賞金')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='募集内容')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='応募資格')),
                ('sponsor', models.TextField(blank=True, null=True, verbose_name='主催')),
                ('link', models.TextField(blank=True, null=True, verbose_name='応募リンク')),
            ],
            options={
                'verbose_name_plural': 'Kobo_info',
            },
        ),
    ]
