# Generated by Django 3.2.9 on 2022-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saiten_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=80, verbose_name='品詞文字列')),
                ('winningCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='入賞頻度')),
            ],
            options={
                'verbose_name_plural': 'Saiten_info',
            },
        ),
    ]
